### ISSUE TITLE
Ads displaying incorrectly

### ISSUE THREAD

**Issue by margopruul** [adform/adform-ios-sdk#26]
### Banners sometimes display incorrectly in our iOS native app using Adform SDK.

Banners are made using software like Adobe Animate CC by desktoppers that do not add or edit extra code.

We receive responsive banners made by clients, upload them to Adform Studio where we set the type of banner to mobile standard, size to 300x250px, add the global clicktag (all that to make the banners mraid compatible) and from there, we upload to Adform. The same banners are used in our web placements and work correctly.

Only way to check if the banner is broken is in the live app with active line items.

#### Screenshot of how the banners are broken
<img src="https://user-images.githubusercontent.com/41049341/42499622-ea8707ea-8437-11e8-9998-320f15051ddc.png" width="600">

#### Screenshot of how they should display
<img src="https://user-images.githubusercontent.com/41049341/42499638-f2beb93a-8437-11e8-9403-78e0225b674b.png" width="600">

#### The banners in question
[aatrium-SIVA-mdelfi-et-600x500.zip](https://github.com/adform/adform-ios-sdk/files/2179601/aatrium-SIVA-mdelfi-et-600x500.zip)
[hyundai-i30-mdelfi-family-ET-600x500.zip](https://github.com/adform/adform-ios-sdk/files/2179602/hyundai-i30-mdelfi-family-ET-600x500.zip)
[Vaikelaen Remont Delfi 600x500 Est.zip](https://github.com/adform/adform-ios-sdk/files/2179603/Vaikelaen.Remont.Delfi.600x500.Est.zip)

#### The code snipped used in app to display banners

```
self.adformNode = ASDisplayNode(viewBlock: { () -> UIView in
    let adView = AFAdInline(masterTagId: placmentIdFromFeed, presenting: self.controller) //  , adSize: AFSmartAdSize

    adView?.delegate = self
    adView?.keywords = self.viewModel?.keywords
    adView?.keyValues = AFKeyValuesFromNSDictionary((self.viewModel?.keyValues)!)

    adView?.areAditionalDimmensionsEnabled = true;
    adView?.supportedDimmensions = [
        AFAdDimension(CGFloat(self.bannerWidth), CGFloat(self.bannerHeight))
    ]

    adView?.loadAd()
    return adView!
})
```
#### Retargeting pixel
To repo the issue I created a line item that shows exclusively those banners in our app. The line item is targeted at a reta pixel:
```
<!-- Pixel: "iOS_Native_App" -->
<img src="https://track.adform.net/Serving/TrackPoint/?pm=945408&lid=40754923" width="1" height="1" alt="" />
```

**Comment by vladasdrejeris** [comment]
Hello,

Maybe you could give us your master tag, or create a separate one, so that we could load your banners in a sample app and try to debug your problem?

One more thing, what iOS version and devices are you using that show this problem?

**Comment by margopruul** [comment]
Hello,

I created a new master tag for you in our test platform and set up a campaign to show only those three banners.

> Adform publisher tag
Tag for test 2pp (iOS) - iOS Est 300x250 mobile placement - 585359

As for what iOS version and devices, I personally saw issues on:
>iPhone X iOS version 11.4
iPhone 6+ iOS version 12.0
iPhone 6 iOS version 11.4

But also received emails and heard from other sources that the same issue was on
> iPhone SE iOS version unknown

**Comment by vladasdrejeris** [comment]
Hello,

I am having issues loading banners with master tag that you provided. 
Could you check if the placement is configured correctly and you are able to load ads with this tag yourself?

**Comment by margopruul** [comment]
I noticed that I had copied the wrong placement id. I am very sorry about that. I updated the previous comment and will add it here too.

> Adform publisher tag
Tag for test 2pp (iOS) - iOS Est 300x250 mobile placement - 585359

Hope this helps.

**Comment by margopruul** [comment]
Hello,

Any update on this issue?

**Comment by vladasdrejeris** [comment]
Hello,

Sorry for long delay. We have identified couple of problems and are looking for ways to solve them.

**Comment by braizhas** [comment]
Ad display issues are fixed now.
"Vaikelaen Remont" banner also needs small change in its styling rules.
Current:
```css
.bg1 {
	top: 0;
	opacity: 1;
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
	-webkit-animation: bg1 14s infinite;
	animation: bg1 14s infinite
}
```
Updated:
```css
.bg1 {
        left: 0;
	top: 0;
	opacity: 1;
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
	-webkit-animation: bg1 14s infinite;
	animation: bg1 14s infinite
}
```

**Comment by margopruul** [comment]
Thank you for the update.

I tested the same banners and they are still broken. (screenshots below) Do we need to have a SDK update or something to see them fixed? Atm we exclude banners from native app as we notice them broken, would like to not have to do that.

And I do not understand why do I have to have the "Väikelaen Remont" banner fixed just for app. The banner works everywhere else.
I mean, it is ok if this is a one time thing and we don't have to start fixing every banner that sets an element position style value to absolute and forgets to specify the left value (which defaults to 0 as far as I know)

![still_broken](https://user-images.githubusercontent.com/41049341/43504768-3fdd4650-956d-11e8-93f9-3a841af4cb13.jpg)

Screenshots taken using iPhone X on 01.08.2018

**Comment by braizhas** [comment]
@margopruul sorry, notified you before fix was released, now banners should be rendered as expected.
Regarding style - we will update SDK to not broke default behaviour, it should be one time fix.

**Comment by margopruul** [comment]
@braizhas and @vladasdrejeris thank you. Tested again this morning and everything is as it should. Banners display correctly. Great work. I consider this issue resolved and closed. High five!
